### ISSUE TITLE
De-duplicate detection and omission

### ISSUE THREAD

**Issue by AndrewFarley** [terraform-aws-modules/terraform-aws-notify-slack#144]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Yes, one direct use-case is when using GuardDuty on multiple regions account-level issues will all generate the same(ish) output and cause some insane spam on your Slack channel.

## Describe the solution you'd like.
An option to enable/disable some intelligent duplicate detection within' this stack.  This could be globally, or per alert-type.  This could be rather simple or extremely complex.

## Describe alternatives you've considered.
I suppose a "de-dupe" SNS forwarding topic/service could be used instead if such an thing exists.  A google search didn't find any such examples out there.

## Additional context
See example: 
<img width="599" alt="Screen Shot 2021-07-13 at 5 26 21 AM" src="https://user-images.githubusercontent.com/470163/125330507-fa600e80-e39a-11eb-91c7-a5d2831267ff.png">

**Comment by AndrewFarley** [comment]
Note: This feature depending how it is implemented may end up making this stack cost quite a bit more to host by having to have an ElasticCache deployed.  Alternatively, could use something more serverless-friendly like DynamoDB which would have minimal added cost and complexity to this stack.  Either way it adds to this stack's complexity.

**Comment by AndrewFarley** [comment]
un-stale

**Comment by antonbabenko** [comment]
I don't think we will be adding such deduplication logic into the module because this module does just one thing - forward messages to Slack.

In order to achieve the deduplication logic, it has to happen before calling this module.

Something like, `GuardDuty/CloudTrail/etc` -> `SNS topic` -> `SQS queue to implement deduplication` ([read more](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html)) -> `SNS topic clean` -> `This module to deliver message to Slack`.

So, I am going to close this issue.
