### ISSUE TITLE
\n newlines are not working with this module

### ISSUE THREAD

**Issue by e-moshaya** [terraform-aws-modules/terraform-aws-notify-slack#37]
I'm using this module for AWS Budgets notifications. However, messages appear in slack from aws budgets with \n not breaking lines.

![Screenshot 2019-07-04 at 20 43 04](https://user-images.githubusercontent.com/44640934/60685680-5898b380-9e9c-11e9-9b6e-112037e2fed9.png)

**Comment by mr337** [comment]
I ran into the same issue, the quick fix was to remove the `json.dumps` at https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/functions/notify_slack.py#L42.

I have been testing this in a deployment and so far everything is working properly since it is dumped later before sending. Still evaluating if it broke something else before I submit a PR.

**Comment by mr337** [comment]
@e-moshaya If you have a chance to test this https://github.com/terraform-aws-modules/terraform-aws-notify-slack/pull/52 please do!

**Comment by antonbabenko** [comment]
@e-moshaya This is now fixed in [v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v2.7.0).

**Comment by mr337** [comment]
Thanks!
